# Generated by Django 6.0.6 on 2026-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "organization"], name="accounts_me_user_id_ca92ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["organization", "role"], name="accounts_me_organiz_91db9c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="unique_user_organization"
            ),
        ),
    ]
