repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        # -r: recursive, -x: exclude directories, -ll: low severity level, -ii: low confidence level
        args: ["-x", "venv,tests", "-ll", "-ii"]